/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e2e2e2",
        "tertiary-fixed-dim": "#84d1f2",
        "on-secondary-fixed-variant": "#852400",
        "on-tertiary-container": "#bfeaff",
        "tertiary": "#00546c",
        "surface-container": "#eeeeee",
        "on-primary-fixed-variant": "#004d63",
        "on-tertiary-fixed-variant": "#004d63",
        "on-primary": "#ffffff",
        "inverse-surface": "#2f3131",
        "on-primary-fixed": "#001f29",
        "tertiary-fixed": "#bce9ff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#82d1f2",
        "inverse-on-surface": "#f1f1f1",
        "on-background": "#1a1c1c",
        "on-surface-variant": "#3f484d",
        "surface-tint": "#006783",
        "surface-container-highest": "#e2e2e2",
        "outline": "#6f787e",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary-container": "#5b1500",
        "surface-dim": "#dadada",
        "primary-container": "#006e8c",
        "surface-container-low": "#f4f3f3",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#001f29",
        "error-container": "#ffdad6",
        "secondary-container": "#fe6431",
        "surface-container-lowest": "#ffffff",
        "primary": "#00546c",
        "surface-container-high": "#e8e8e8",
        "primary-fixed": "#bce9ff",
        "secondary": "#ae3100",
        "outline-variant": "#bfc8cd",
        "on-primary-container": "#bfeaff",
        "tertiary-container": "#076e8c",
        "on-secondary-fixed": "#3a0a00",
        "secondary-fixed-dim": "#ffb59f",
        "inverse-primary": "#82d1f2",
        "surface": "#f9f9f9",
        "on-surface": "#1a1c1c",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#ffdbd0",
        "background": "#f9f9f9",
        "surface-bright": "#f9f9f9",
        "accent-orange": "#f05a28",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        xl: "64px",
        lg: "40px",
        "margin-mobile": "16px",
        base: "8px",
        md: "24px",
        xs: "4px",
        gutter: "24px",
        sm: "12px",
      },
      fontFamily: {
        montserrat: ["Montserrat", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
      boxShadow: {
        "teal": "0px 4px 12px rgba(0, 110, 140, 0.08)",
        "teal-hover": "0px 8px 20px rgba(0, 110, 140, 0.12)",
        "teal-lg": "0px 12px 28px rgba(0, 110, 140, 0.15)",
      },
      keyframes: {
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideInLeft: {
          "0%": { opacity: "0", transform: "translateX(-30px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        slideInRight: {
          "0%": { opacity: "0", transform: "translateX(30px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
      },
      animation: {
        "fade-in-up": "fadeInUp 0.6s ease-out both",
        "fade-in": "fadeIn 0.4s ease-out both",
        "slide-in-left": "slideInLeft 0.6s ease-out both",
        "slide-in-right": "slideInRight 0.6s ease-out both",
        "float": "float 3s ease-in-out infinite",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
}
